"""HRG-5: Base images review panel. S-05 output — 6 images with CLIP scores."""
from __future__ import annotations


def render(job_id: str, scene_id: str, api_base: str = "http://localhost:8000/api/v1") -> None:
    import streamlit as st

    st.header("🖼️ HRG-5: Base Image Review")
    st.caption("Review 6 base character images. Each must score CLIP ≥ 0.93 (RULE-92). NO LoRA used (RULE-91).")
    st.info("6 base images generated by FLUX.2-klein-4B without LoRA. Select best candidate for identity reinforcement.")

    col1, col2 = st.columns(2)
    with col1:
        if st.button("✅ Approve Best Image", key=f"hrg5_approve_{job_id}"):
            _submit(api_base, job_id, "HRG-5", scene_id, "approved")
            st.success("Base images approved")
    with col2:
        if st.button("❌ Reject & Regenerate", key=f"hrg5_reject_{job_id}"):
            _submit(api_base, job_id, "HRG-5", scene_id, "rejected")


def _submit(api_base, job_id, cp, scene_id, decision, reason=""):
    import requests
    try:
        requests.post(f"{api_base}/hrg/decision", json={"checkpoint": cp, "scene_id": scene_id, "job_id": job_id, "decision": decision, "reason": reason}, timeout=10)
    except Exception:
        pass
