"""
EndFrameGeneratorAgent — Stage S-07c: generates FLF2V end frames for each segment.

Two-step process per segment:
  1. FLUX.2-klein generates a scene-state image from the segment's action_description
     (no LoRA — end frames show scene composition, not character close-ups).
  2. Z-Image-Turbo polishes the FLUX output at denoise=FLF2V_ZIMAGE_DENOISE (0.10)
     — same conservative strength as S-07 character refinement — sharpening edges
     and texture without altering scene composition or character identity.

Only runs when FLF2V_ENABLED = True. Skipped entirely when FLF2V is off.
Populates SegmentPlanSchema.end_frame_path for segments 2..N (used by TemporalEngine).

Spec: VGA System Architecture v17.2 §FLF2V; RULE-88 (CompositionPlan required)
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import List, Optional, Tuple

from vga.agents.base_agent import BaseAgent
from vga.config.settings import settings
from vga.models.schemas import ScenePlanSchema, SegmentPlanSchema
from vga.models.wrappers.flux_wrapper import FluxWrapper
from vga.models.wrappers.z_image_wrapper import ZImageWrapper
from vga.state.immutable_context import ImmutableContext

logger = logging.getLogger(__name__)


class EndFrameGeneratorAgent(BaseAgent):
    """S-07c: generates + polishes FLF2V end frames for SVI continuation segments.

    End frames constrain where each video segment ends visually.
    Each frame is generated by FLUX (scene state) then polished by Z-Image-Turbo
    (edge sharpening at denoise=0.10 — identity-safe refinement).

    When FLF2V_ENABLED = False, run() returns immediately without generating
    anything, leaving all end_frame_path fields as None.
    """

    stage_id = "S-07c"

    def __init__(
        self,
        flux: Optional[FluxWrapper] = None,
        zimage: Optional[ZImageWrapper] = None,
    ) -> None:
        self._flux = flux or FluxWrapper()
        self._zimage = zimage or ZImageWrapper()
        logger.info(
            "EndFrameGeneratorAgent initialized — FLF2V_ENABLED=%s, ZIMAGE_POLISH=%s",
            settings.FLF2V_ENABLED,
            settings.FLF2V_ZIMAGE_POLISH,
        )

    def run(
        self,
        input_data: dict,
        context: ImmutableContext,
    ) -> Tuple[dict, ImmutableContext]:
        """Generate FLF2V end frames for all segments in the scene plan.

        Args:
            input_data: dict with keys:
                scene_plan          — ScenePlanSchema
                composition_plan    — CompositionPlanSchema (RULE-88 required)
                character_description — brief character appearance string
                output_dir          — str path where end frames are saved

            context: current ImmutableContext (identity must be frozen — called after S-07)

        Returns:
            (result_dict, new_context) where result_dict contains:
                scene_plan          — ScenePlanSchema with end_frame_path populated
                end_frames_generated — int count of frames generated
                schema_version      — "v6.0"
        """
        self._log_start(context.scene_id)

        scene_plan: ScenePlanSchema = input_data["scene_plan"]
        composition_plan = input_data["composition_plan"]
        character_description: str = input_data.get("character_description", "")
        output_dir = Path(input_data["output_dir"])

        if not settings.FLF2V_ENABLED:
            logger.info(
                "EndFrameGeneratorAgent: FLF2V_ENABLED=False — skipping end frame generation"
            )
            self._log_complete(context.scene_id)
            return {
                "scene_plan": scene_plan,
                "end_frames_generated": 0,
                "schema_version": settings.SCHEMA_VERSION,
            }, context

        # End frames are used by TemporalEngine for segments 2..N.
        # We generate for all segments; segment 1's end frame is available but
        # only consumed if S-08 (Wan2.2 I2V) is upgraded to support it natively.
        end_frames_dir = output_dir / "end_frames" / scene_plan.scene_id
        end_frames_dir.mkdir(parents=True, exist_ok=True)

        generated_count = 0
        updated_segments: List[SegmentPlanSchema] = []

        for plan in scene_plan.segments:
            updated_plan = self._generate_for_segment(
                plan=plan,
                composition_plan=composition_plan,
                character_description=character_description,
                end_frames_dir=end_frames_dir,
            )
            updated_segments.append(updated_plan)
            if updated_plan.end_frame_path:
                generated_count += 1

        # Reconstruct scene_plan with updated segments (Pydantic v2 model_copy)
        updated_scene_plan = scene_plan.model_copy(
            update={"segments": updated_segments}
        )

        logger.info(
            "EndFrameGeneratorAgent: generated %d end frames for scene %s",
            generated_count, scene_plan.scene_id,
        )
        self._log_complete(context.scene_id)

        return {
            "scene_plan": updated_scene_plan,
            "end_frames_generated": generated_count,
            "schema_version": settings.SCHEMA_VERSION,
        }, context

    # ─── Private ─────────────────────────────────────────────────────────────

    def _generate_for_segment(
        self,
        plan: SegmentPlanSchema,
        composition_plan,
        character_description: str,
        end_frames_dir: Path,
    ) -> SegmentPlanSchema:
        """Generate + polish one end frame, return updated SegmentPlanSchema."""
        save_path = end_frames_dir / f"segment_{plan.segment_number:03d}_end.png"

        # Skip if already generated (allows resume after partial failure)
        if save_path.exists():
            logger.info(
                "EndFrameGeneratorAgent: segment %d end frame exists — reusing %s",
                plan.segment_number, save_path.name,
            )
            return plan.model_copy(update={"end_frame_path": str(save_path)})

        logger.info(
            "EndFrameGeneratorAgent: segment %d — generating end frame via FLUX",
            plan.segment_number,
        )

        # Step 1: FLUX generates the scene-state end frame.
        # Seed varies per segment so consecutive end frames differ compositionally.
        seed = 100 + plan.segment_number
        end_frame = self._flux.generate_end_frame(
            action_description=plan.action_description,
            composition_plan=composition_plan,
            character_description=character_description,
            seed=seed,
        )

        # Step 2: Z-Image-Turbo polishes the FLUX output.
        # denoise=FLF2V_ZIMAGE_DENOISE (0.10) — sharpens without composition change.
        # The prompt is the action_description so Z-Image steers toward scene fidelity.
        if settings.FLF2V_ZIMAGE_POLISH:
            logger.info(
                "EndFrameGeneratorAgent: segment %d — Z-Image-Turbo polish "
                "(denoise=%.2f)",
                plan.segment_number, settings.FLF2V_ZIMAGE_DENOISE,
            )
            end_frame = self._zimage.refine(
                image=end_frame,
                prompt=f"{plan.action_description}, cinematic, sharp, detailed",
                strength=settings.FLF2V_ZIMAGE_DENOISE,
                seed=seed,
            )

        # Save to disk
        end_frame.save(str(save_path), format="PNG")
        logger.info(
            "EndFrameGeneratorAgent: segment %d end frame saved → %s",
            plan.segment_number, save_path.name,
        )

        return plan.model_copy(update={"end_frame_path": str(save_path)})

    def _log_start(self, scene_id: str) -> None:
        logger.info("EndFrameGeneratorAgent: START scene=%s", scene_id)

    def _log_complete(self, scene_id: str) -> None:
        logger.info("EndFrameGeneratorAgent: COMPLETE scene=%s", scene_id)
