"""
VideoSegmentGenerator — Stage S-08 (NEW v17.0): generates Segment_1 via Wan2.2.
Initializes TemporalBuffer from Segment_1 (exactly 5 frames, RULE-86).
CompositionPlan required (RULE-88). CLIP ≥ 0.93 (RULE-89). Identity frozen (RULE-95).
Spec: VGA Temporal Engine Spec v17.2 §S-08; RULE-86, RULE-88, RULE-89, RULE-95
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Tuple

from vga.agents.base_agent import BaseAgent
from vga.config.settings import settings
from vga.models.schemas import VideoSegmentArtifact
from vga.models.wrappers.wan_wrapper import WanWrapper
from vga.state.immutable_context import ImmutableContext, TemporalState
from vga.temporal.temporal_buffer_manager import TemporalBuffer, TemporalBufferManager
from vga.validation.clip_validator import CLIPValidator

logger = logging.getLogger(__name__)


class VideoSegmentGenerator(BaseAgent):
    """S-08 (NEW v17.0): generates Segment_1 from the refined image using Wan2.2-I2V.

    This agent ONLY generates Segment_1.
    Segments 2..N are generated by TemporalEngine (S-09).
    """

    stage_id = "S-08"

    def __init__(
        self,
        wan: WanWrapper | None = None,
        buffer_manager: TemporalBufferManager | None = None,
        clip_validator: CLIPValidator | None = None,
    ) -> None:
        self._wan = wan or WanWrapper()
        self._buffer_manager = buffer_manager or TemporalBufferManager()
        self._clip = clip_validator or CLIPValidator()

    def run(
        self,
        input_data: dict,
        context: ImmutableContext,
    ) -> Tuple[dict, ImmutableContext]:
        """Generate Segment_1 from refined image and initialize TemporalBuffer.

        Args:
            input_data: dict with refined_image (PIL Image), output_dir (str)
            context:    must have frozen identity (RULE-95) and CompositionPlan (RULE-88)

        Returns:
            (output dict with segment_1 artifact + buffer, new_context)
        """
        self._log_start(context.scene_id)
        context.assert_composition_plan()    # RULE-88
        context.assert_identity_frozen()     # RULE-95

        refined_image = input_data["refined_image"]
        output_dir = Path(input_data.get("output_dir", settings.OUTPUT_DIR / context.job_id))
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / "segment_001.mp4"

        plan = context.composition_plan

        # Generate Segment_1 via Wan2.2-I2V (RULE-88: pass composition motion fields)
        segment_1 = self._wan.generate(
            init_image=refined_image,
            prompt=input_data.get("prompt", "cinematic scene"),
            composition_plan=plan,
            output_path=output_path,
        )
        segment_1 = segment_1.model_copy(update={"scene_id": context.scene_id})

        # CLIP validate Segment_1 keyframe (RULE-89)
        # I2V-generated scene frames naturally score much lower than close-up character references.
        # Hard floor (CLIP_S08_I2V_MINIMUM=0.15) catches truly broken/black outputs.
        # Soft floor (CLIP_VIDEO_SEGMENT_MINIMUM=0.75) is warn-only — identity is already frozen at S-07.
        keyframe = self._extract_keyframe(output_path)
        clip_score = self._clip.score(keyframe, context.identity_state.embedding_vector)
        if clip_score < settings.CLIP_I2V_HARD_FLOOR:
            self._clip.assert_above_threshold(clip_score, self.stage_id, context.scene_id)
        elif clip_score < settings.CLIP_VIDEO_SEGMENT_MINIMUM:
            logger.warning(
                "VideoSegmentGenerator: Segment_1 CLIP=%.4f below soft floor %.2f — "
                "I2V scene frames naturally score lower than close-up reference; continuing",
                clip_score, settings.CLIP_VIDEO_SEGMENT_MINIMUM,
            )
        elif clip_score < settings.CLIP_IDENTITY_THRESHOLD:
            logger.warning("VideoSegmentGenerator: Segment_1 CLIP=%.4f (below 0.93 — acceptable for I2V scene output)", clip_score)
        else:
            logger.info("VideoSegmentGenerator: Segment_1 CLIP=%.4f ✅", clip_score)

        # Initialize TemporalBuffer from Segment_1 (RULE-86: exactly 5 frames)
        buffer = self._buffer_manager.init(str(output_path))
        self._buffer_manager._assert_buffer_size(buffer)  # assert 5 frames

        # Write segment_1 path to context as stage output + update temporal state
        new_context = context.evolve(
            current_stage=self.stage_id,
            temporal_state=TemporalState(
                segment_index=1,
                total_segments=context.temporal_state.total_segments,
                buffer_initialized=True,
            ),
        )

        output = {
            "segment_1": segment_1,
            "buffer": buffer,
            "clip_score": clip_score,
            "scene_id": context.scene_id,
            "schema_version": settings.SCHEMA_VERSION,
        }

        self._log_complete(context.scene_id)
        return output, new_context

    @staticmethod
    def _extract_keyframe(video_path: Path) -> "PIL.Image.Image":
        """Extract middle frame of video for CLIP scoring."""
        try:
            import cv2
            from PIL import Image
            cap = cv2.VideoCapture(str(video_path))
            total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            cap.set(cv2.CAP_PROP_POS_FRAMES, total // 2)
            ret, frame = cap.read()
            cap.release()
            if ret:
                return Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        except Exception:
            pass
        from PIL import Image
        return Image.new("RGB", (512, 512))
