"""
WanWrapper — wraps Wan2.2-I2V-A14B-FP8 for Segment_1 generation.
S-08 (VideoSegmentGenerator): generates first video segment from refined image.
CompositionPlan motion_vector and camera_motion REQUIRED (RULE-88, FR-981).
Spec: VGA Model Stack Setup Guide v7.2 §2.4
"""
from __future__ import annotations

import json
import logging
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Optional

from vga.config.settings import settings
from vga.core.exceptions import CompositionPlanValidationError, ModelLoadError
from vga.models.schemas import CompositionPlanSchema, VideoSegmentArtifact

logger = logging.getLogger(__name__)

_DIFFSYNTH_AVAILABLE: bool | None = None


def _has_diffsynth() -> bool:
    global _DIFFSYNTH_AVAILABLE
    if _DIFFSYNTH_AVAILABLE is None:
        try:
            import diffsynth  # noqa: F401
            from diffsynth.models.wan_video_dit import WanModel  # noqa: F401
            _DIFFSYNTH_AVAILABLE = True
        except ImportError:
            _DIFFSYNTH_AVAILABLE = False
    return _DIFFSYNTH_AVAILABLE


class WanWrapper:
    """Wraps Wan2.2-I2V-A14B-FP8 for image-to-video generation (Segment_1 only).

    Segments 2..N are generated by TemporalEngine via SVI Pro 2.
    This wrapper ONLY generates Segment_1 (S-08).
    """

    MODEL_KEY = "wan22-i2v"

    def __init__(self) -> None:
        self._pipe = None
        logger.info("WanWrapper initialized (lazy load)")

    def generate(
        self,
        init_image: "PIL.Image.Image",
        prompt: str,
        composition_plan: CompositionPlanSchema,
        output_path: str | Path,
        num_frames: int = 81,
        fps: int = 15,
        seed: int = 42,
    ) -> VideoSegmentArtifact:
        """Generate Segment_1 from init_image using Wan2.2-I2V.

        RULE-88: composition_plan is required (motion_vector and camera_motion).
        This generates ONLY Segment_1. TemporalEngine handles all subsequent segments.

        Args:
            init_image:       the refined character image (from S-07)
            prompt:           scene description prompt
            composition_plan: required CompositionPlan with motion_vector + camera_motion
            output_path:      where to write segment_001.mp4
            num_frames:       number of video frames (default 81 → ~5.4s at 15fps)
            fps:              frames per second
            seed:             random seed

        Returns:
            VideoSegmentArtifact with segment metadata
        """
        if composition_plan is None:
            raise CompositionPlanValidationError(
                "WanWrapper.generate() requires a CompositionPlan. RULE-88."
            )

        self._ensure_loaded()
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        if self._pipe == "diffsynth_subprocess":
            self._generate_via_subprocess(
                init_image, prompt, composition_plan, output_path,
                num_frames=num_frames, fps=fps, seed=seed,
            )
        elif self._pipe == "ffmpeg_fallback":
            logger.info("WanWrapper: using ffmpeg still-image fallback for Segment_1")
            self._create_still_video(init_image, output_path, fps=fps, num_frames=num_frames)
        else:
            full_prompt = self._build_prompt(prompt, composition_plan)
            logger.info(
                "WanWrapper: generating Segment_1 motion_vector=%s camera=%s",
                composition_plan.motion_vector, composition_plan.camera_motion,
            )
            try:
                import torch
                generator = torch.Generator().manual_seed(seed)
                output = self._pipe(
                    image=init_image,
                    prompt=full_prompt,
                    num_frames=num_frames,
                    guidance_scale=5.0,
                    num_inference_steps=20,
                    generator=generator,
                )
                frames = output.frames[0]
                self._save_video(frames, output_path, fps=fps)
            except Exception as exc:
                raise ModelLoadError(f"WanWrapper inference failed: {exc}") from exc

        duration_s = num_frames / fps
        return VideoSegmentArtifact(
            segment_id="segment_001",
            scene_id="",   # set by caller
            segment_number=1,
            file_path=str(output_path),
            duration_s=duration_s,
            keyframe_path=str(output_path),   # updated by caller after extraction
        )

    def _ensure_loaded(self) -> None:
        """Lazy-load Wan2.2-I2V pipeline.

        Prefer DiffSynth subprocess (SVI native FP8 format) if diffsynth is importable.
        Falls back to ffmpeg still-image video when diffsynth is unavailable.
        """
        if self._pipe is not None:
            return
        if _has_diffsynth():
            logger.info("WanWrapper: DiffSynth available — will use SVI subprocess for Segment_1")
            self._pipe = "diffsynth_subprocess"
        else:
            logger.warning(
                "WanWrapper: diffsynth not available — using ffmpeg still-image fallback. "
                "Install vita-epfl/Stable-Video-Infinity (svi_wan22 branch) for real I2V.",
            )
            self._pipe = "ffmpeg_fallback"

    def _generate_via_subprocess(
        self,
        init_image: "PIL.Image.Image",
        prompt: str,
        composition_plan: CompositionPlanSchema,
        output_path: Path,
        num_frames: int = 81,
        fps: int = 15,
        seed: int = 42,
    ) -> None:
        """Generate Segment_1 via DiffSynth SVI subprocess with native FP8 format."""
        inference_script = Path("/workspace/scripts/vga_svi_inference.py")
        if not inference_script.exists():
            logger.warning("WanWrapper: vga_svi_inference.py not found, falling back to ffmpeg")
            self._create_still_video(init_image, output_path, fps=fps, num_frames=num_frames)
            return

        # Save init_image to temp file for subprocess
        tmp_img_path = None
        cfg_path = None
        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as f:
            tmp_img_path = f.name
        try:
            init_image.save(tmp_img_path, quality=95)
            full_prompt = self._build_prompt(prompt, composition_plan)
            lora_high = str(settings.SVI_HIGH_NOISE_PATH)
            lora_low = str(settings.SVI_LOW_NOISE_PATH)
            config = {
                "init_image_path": tmp_img_path,
                "output_path": str(output_path),
                "prompt": full_prompt,
                "cfg": settings.SVI_CFG_DEFAULT,
                "steps": settings.STEPS_STANDARD,
                "camera_motion": composition_plan.camera_motion,
                "motion_vector": composition_plan.motion_vector,
                "lora_path_high": lora_high,
                "lora_path_low": lora_low,
                "tea_cache_l1_thresh": 0.1,
            }
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".json", delete=False
            ) as cfg_f:
                cfg_path = cfg_f.name
                json.dump(config, cfg_f)

            logger.info(
                "WanWrapper: spawning DiffSynth I2V subprocess (Segment_1) cfg=%.1f steps=%d",
                config["cfg"], config["steps"],
            )
            result = subprocess.run(
                [sys.executable, str(inference_script), "--config", cfg_path],
                capture_output=False,
                timeout=1800,
            )
            if result.returncode != 0:
                logger.warning(
                    "WanWrapper: DiffSynth subprocess failed (rc=%d), falling back to ffmpeg",
                    result.returncode,
                )
                self._create_still_video(init_image, output_path, fps=fps, num_frames=num_frames)
        except Exception as exc:
            logger.warning("WanWrapper: DiffSynth subprocess error: %s — ffmpeg fallback", exc)
            self._create_still_video(init_image, output_path, fps=fps, num_frames=num_frames)
        finally:
            import os
            for p in [tmp_img_path, cfg_path]:
                if p:
                    try:
                        os.unlink(p)
                    except OSError:
                        pass

    @staticmethod
    def _build_prompt(base_prompt: str, plan: CompositionPlanSchema) -> str:
        """Build generation prompt incorporating CompositionPlan motion fields."""
        return (
            f"{base_prompt}, "
            f"{plan.camera_motion}, "
            f"{plan.lighting_style} lighting, "
            f"motion: {plan.motion_vector}, "
            f"cinematic quality, photorealistic"
        )

    @staticmethod
    def _save_video(
        frames: list,
        output_path: Path,
        fps: int = 15,
    ) -> None:
        """Save list of PIL frames as MP4 video."""
        try:
            import imageio
            imageio.mimwrite(str(output_path), frames, fps=fps, quality=8)
        except ImportError:
            try:
                import cv2
                import numpy as np
                if frames:
                    h, w = frames[0].size[1], frames[0].size[0]
                    writer = cv2.VideoWriter(
                        str(output_path),
                        cv2.VideoWriter_fourcc(*"mp4v"),
                        fps,
                        (w, h),
                    )
                    for frame in frames:
                        writer.write(cv2.cvtColor(
                            cv2.cvtColor(__import__("numpy").array(frame), cv2.COLOR_RGB2BGR),
                            cv2.COLOR_BGR2BGR,
                        ))
                    writer.release()
            except Exception as exc:
                logger.error("WanWrapper: failed to save video: %s", exc)

    @staticmethod
    def _create_still_video(
        image: "PIL.Image.Image",
        output_path: Path,
        fps: int = 15,
        num_frames: int = 81,
    ) -> None:
        """Create a still-image looped video via ffmpeg (fallback for testing)."""
        import subprocess
        import tempfile
        duration = num_frames / fps
        with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as f:
            tmp_img = f.name
        image.save(tmp_img, quality=95)
        try:
            subprocess.run([
                "ffmpeg", "-y", "-loop", "1", "-i", tmp_img,
                "-c:v", "libx264", "-t", str(duration),
                "-vf", f"fps={fps},scale=832:480",
                "-pix_fmt", "yuv420p",
                str(output_path),
            ], check=True, capture_output=True)
            logger.info("WanWrapper: still-image video created at %s", output_path)
        finally:
            import os
            os.unlink(tmp_img)
