"""
WanWrapper — wraps Wan2.2-I2V-A14B-FP8 for Segment_1 generation.
S-08 (VideoSegmentGenerator): generates first video segment from refined image.
CompositionPlan motion_vector and camera_motion REQUIRED (RULE-88, FR-981).
Spec: VGA Model Stack Setup Guide v7.2 §2.4
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from vga.config.settings import settings
from vga.core.exceptions import CompositionPlanValidationError, ModelLoadError
from vga.models.schemas import CompositionPlanSchema, VideoSegmentArtifact

logger = logging.getLogger(__name__)


class WanWrapper:
    """Wraps Wan2.2-I2V-A14B-FP8 for image-to-video generation (Segment_1 only).

    Segments 2..N are generated by TemporalEngine via SVI Pro 2.
    This wrapper ONLY generates Segment_1 (S-08).
    """

    MODEL_KEY = "wan22-i2v"

    def __init__(self) -> None:
        self._pipe = None
        logger.info("WanWrapper initialized (lazy load)")

    def generate(
        self,
        init_image: "PIL.Image.Image",
        prompt: str,
        composition_plan: CompositionPlanSchema,
        output_path: str | Path,
        num_frames: int = 81,
        fps: int = 15,
        seed: int = 42,
    ) -> VideoSegmentArtifact:
        """Generate Segment_1 from init_image using Wan2.2-I2V.

        RULE-88: composition_plan is required (motion_vector and camera_motion).
        This generates ONLY Segment_1. TemporalEngine handles all subsequent segments.

        Args:
            init_image:       the refined character image (from S-07)
            prompt:           scene description prompt
            composition_plan: required CompositionPlan with motion_vector + camera_motion
            output_path:      where to write segment_001.mp4
            num_frames:       number of video frames (default 81 → ~5.4s at 15fps)
            fps:              frames per second
            seed:             random seed

        Returns:
            VideoSegmentArtifact with segment metadata
        """
        if composition_plan is None:
            raise CompositionPlanValidationError(
                "WanWrapper.generate() requires a CompositionPlan. RULE-88."
            )

        self._ensure_loaded()
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        full_prompt = self._build_prompt(prompt, composition_plan)
        logger.info(
            "WanWrapper: generating Segment_1 motion_vector=%s camera=%s",
            composition_plan.motion_vector, composition_plan.camera_motion,
        )

        try:
            import torch
            generator = torch.Generator().manual_seed(seed)
            output = self._pipe(
                image=init_image,
                prompt=full_prompt,
                num_frames=num_frames,
                guidance_scale=5.0,
                num_inference_steps=20,
                generator=generator,
            )
            frames = output.frames[0]
            self._save_video(frames, output_path, fps=fps)
        except Exception as exc:
            raise ModelLoadError(f"WanWrapper inference failed: {exc}") from exc

        duration_s = num_frames / fps
        return VideoSegmentArtifact(
            segment_id="segment_001",
            scene_id="",   # set by caller
            segment_number=1,
            file_path=str(output_path),
            duration_s=duration_s,
            keyframe_path=str(output_path),   # updated by caller after extraction
        )

    def _ensure_loaded(self) -> None:
        """Lazy-load Wan2.2-I2V pipeline."""
        if self._pipe is not None:
            return
        try:
            from diffusers import WanImageToVideoPipeline
            import torch
            path = str(settings.WAN22_MODEL_PATH)
            logger.info("WanWrapper: loading from %s", path)
            self._pipe = WanImageToVideoPipeline.from_pretrained(
                path,
                torch_dtype=torch.bfloat16,
            )
            self._pipe.enable_model_cpu_offload()
            logger.info("WanWrapper: Wan2.2-I2V loaded")
        except Exception as exc:
            raise ModelLoadError(f"WanWrapper failed to load: {exc}") from exc

    @staticmethod
    def _build_prompt(base_prompt: str, plan: CompositionPlanSchema) -> str:
        """Build generation prompt incorporating CompositionPlan motion fields."""
        return (
            f"{base_prompt}, "
            f"{plan.camera_motion}, "
            f"{plan.lighting_style} lighting, "
            f"motion: {plan.motion_vector}, "
            f"cinematic quality, photorealistic"
        )

    @staticmethod
    def _save_video(
        frames: list,
        output_path: Path,
        fps: int = 15,
    ) -> None:
        """Save list of PIL frames as MP4 video."""
        try:
            import imageio
            imageio.mimwrite(str(output_path), frames, fps=fps, quality=8)
        except ImportError:
            try:
                import cv2
                import numpy as np
                if frames:
                    h, w = frames[0].size[1], frames[0].size[0]
                    writer = cv2.VideoWriter(
                        str(output_path),
                        cv2.VideoWriter_fourcc(*"mp4v"),
                        fps,
                        (w, h),
                    )
                    for frame in frames:
                        writer.write(cv2.cvtColor(
                            cv2.cvtColor(__import__("numpy").array(frame), cv2.COLOR_RGB2BGR),
                            cv2.COLOR_BGR2BGR,
                        ))
                    writer.release()
            except Exception as exc:
                logger.error("WanWrapper: failed to save video: %s", exc)
