#!/usr/bin/env python3
"""
VGA SVI Inference Bridge — runs inside svi_wan22 conda env.
Called by SVIWrapper via subprocess with a JSON config file.

This script bridges between VGA's pipeline and SVI's inference_svi_2.0.py:
- Receives: JSON config with prev_segment_path, prompt, LoRA paths, output_path
- Extracts: last frame from previous segment as reference image
- Calls: inference_svi_2.0.py to generate next temporal segment
- Returns: 0 on success, non-zero on failure
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path


def extract_last_frame(video_path: str, output_image_path: str) -> bool:
    """Extract last frame from a video file and save as JPEG."""
    try:
        import cv2
        cap = cv2.VideoCapture(video_path)
        total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        cap.set(cv2.CAP_PROP_POS_FRAMES, max(0, total - 1))
        ret, frame = cap.read()
        cap.release()
        if not ret:
            print(f"ERROR: Could not read frame from {video_path}")
            return False
        cv2.imwrite(output_image_path, frame)
        return True
    except Exception as e:
        print(f"ERROR extracting frame: {e}")
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description="VGA SVI Inference Bridge")
    parser.add_argument("--config", required=True, help="Path to JSON config file")
    args = parser.parse_args()

    # Load config
    config_path = Path(args.config)
    if not config_path.exists():
        print(f"ERROR: Config not found: {config_path}")
        return 1

    config = json.loads(config_path.read_text(encoding="utf-8"))

    repo_path = Path(config["repo_path"])
    output_path = Path(config["output_path"])
    prev_segment_path = config.get("prev_segment_path", "")
    prompt = config.get("prompt", "cinematic scene, photorealistic")
    lora_path_high = config["lora_path_high"]
    lora_path_low = config["lora_path_low"]
    cfg = float(config.get("cfg", 5.5))
    steps = int(config.get("steps", 30))
    camera_motion = config.get("camera_motion", "static")
    motion_vector = config.get("motion_vector", "stationary")

    # Validate inputs
    inference_script = repo_path / "inference_svi_2.0.py"
    if not inference_script.exists():
        print(f"ERROR: SVI inference script not found: {inference_script}")
        return 1

    if not prev_segment_path or not Path(prev_segment_path).exists():
        print(f"ERROR: Previous segment not found: {prev_segment_path}")
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Extract last frame from previous segment as reference image
    with tempfile.NamedTemporaryFile(suffix=".jpg", delete=False) as f:
        ref_image_path = f.name
    with tempfile.NamedTemporaryFile(suffix=".txt", delete=False, mode="w") as f:
        f.write(f"{prompt}, {camera_motion}, {motion_vector}")
        prompt_path = f.name

    try:
        if not extract_last_frame(prev_segment_path, ref_image_path):
            return 1

        # Use a temp output dir so SVI doesn't conflict with our output path
        with tempfile.TemporaryDirectory() as tmp_out:
            cmd = [
                sys.executable,
                str(inference_script),
                "--output_root", tmp_out,
                "--height", "480",
                "--width", "832",
                "--lora_path_high", str(lora_path_high),
                "--lora_path_low", str(lora_path_low),
                "--fps", "15",
                "--ref_image_path", ref_image_path,
                "--prompt_path", prompt_path,
                "--num_clips", "1",
            ]

            print(f"Running SVI inference: segment → {output_path.name}")
            result = subprocess.run(cmd, cwd=str(repo_path))

            if result.returncode != 0:
                print(f"ERROR: SVI inference failed with code {result.returncode}")
                return result.returncode

            # Find the generated video in tmp_out and move to output_path
            mp4_files = list(Path(tmp_out).rglob("*.mp4"))
            if not mp4_files:
                print("ERROR: No output video generated by SVI")
                return 1

            # Take the most recently created mp4
            latest_mp4 = max(mp4_files, key=lambda p: p.stat().st_mtime)
            import shutil
            shutil.copy2(str(latest_mp4), str(output_path))
            print(f"SUCCESS: Segment saved to {output_path}")
            return 0

    finally:
        # Cleanup temp files
        for tmp in [ref_image_path, prompt_path]:
            try:
                os.unlink(tmp)
            except OSError:
                pass


if __name__ == "__main__":
    sys.exit(main())
